import pandas as pd

def load_parameters():

   k_neighbors = 5
   ai_model_file = 'models/NearestNeighbors.pkl'

   custom_stopwords = set(["with", "fat", "and", "raw", "cooked", "canned", "frozen", "sauce", "or", "without", "to", 
                      "lean", "cream", "in", "soup", "boiled", "prepared", "fried", "bread", "salt", "deep", "chocolate", "fruit", "white", "made", "drained", "wheat","dry","separable", "from", "salad", "rice", "w", "vegetables", "added", "whole", "1", "potato", "recipe", "free", "water",
                      "dried", "ready", "sweet", "trimmed", "tomato", "oil", "cake", "sugar", "baked",
                      "4", "juice", "butter", "low", "0", "standard", "mixed", "drink",
                      "vegetable", "roll", "6", "smoked", "rye", "5", "no", "medium", "roasted",
                      "cured", "pasta", "flour", "fresh", "skin", "for", "undrained", "only", "based", "of",
                      "mixed", "red", "2", "3", "potatoes", "reduced", "cereals", "sandwich", "dressing",
                      "grilled", "matter", "filled", "loin", "apple", "wholemeal", "ice", "style", "pizza", "min",
                      "vanilla", "cereal", "brown", "plain", "type", "corn", "light",
                      "roast", "braised", "fast", "eat", "all", "carrots", "prepacked", "crispbread", "as", "average", "campbell",
                      "company", "pastry", "pickled", "round", "8", "meal", "coffee", "on", "home", "margarine", "vitamin", "cabbage",
                      "dough", "product", "shoulder", "sour", "bar", "ns", "e.g.",
                      "fortified", "sweetened", "unsweetened", "pudding", "e.g", "food", "jam",
                      "soft", "nfs", "select", "gravy", "pepper", "babyfood", "wine", "not", "biscuit",
                      "semi", "pie", "lactose", "choice", "calorie", "casserole", "crust", "filling", "d", "eaten",
                      "onion", "sodium", "regular", "noodles", "sweetener", "breaded", "multigrain", "top",
                      "mayonnaise", "spread", "products", "cookie", "tomatoes", "syrup", "orange", "1.5", "strawberry",
                      "batter", "baby", "vitamins", "macaroni", "snacks", "cherry", "infant", "hot", "heat", "lettuce", "chips", 
                      "pineapple", "bun", "foods", "3.5","tea", "bottled", "honey", "lemon", "50", "dumplings", "oven",
                      "serve", "candies","dessert", "berry", "unsmoked", "onions", "porridge", "scrambled", "banana", "barley", "toast",
                      "muesli", "o", "calcium", "chili", "30", "a", "alasks", "other", "steamed", "plum", "20", "caramel", "chinese",
                      "nectar", "pan", "wholegrain", "cooking", "cucumber", "italian", "vinegar", "heated", "fruits", "crackers", "peppers", "toasted", "compote",
                      "stock", "beer", "eye", "thin", "40", "liquids", "squash", "jelly", "toddler", "45", "liquid",
                      "blade", "mustard", "asparagus", "kellogg's", "shortcrust", "danish", "raisins", "cookies", "cinnamon", "apricot",
                      "goulash", "pear", "soups", "granola", "garlic", "pumpkin", "torte", "schnitzel",
                      "pack", "olives", "ug", "beetroot", "custard", "decaffeinated", "candy", "peach",
                      "60", "homemade", "noodle", "bakery", "spaghetti", "12", "mcdonald's", "blueberry", "la", "100", "button", "apples", "carbonated",
                      "puerto", "rican", "raspberry", "rolls", "saithe", "alcoholic", "pancakes", "salami",
                      "taco", "tortilla", "c", "diet", "mutton", "alcohol", "dishes", "fibre", "knuckle", "grape", "island",
                      "bologna", "biscuits", "brisket", "mineralized", "muffin", "spices", "topping", "iron", "waffle", "15", "currant", "hock", "iced", "80",
                      "arc", "drumstick", "creamy", "crisp", "drinks", "herb", "pancake", "puff", "rainbow", "tip", "ragout", "than",
                      "boiling", "malt", "pâté", "fidm", "gratin", "kellogg", "loaf", "species", "app", "broth",
                      "curry", "herbs", "smoothie", "stuffed", "mango", "dinner", "refrigerated", "sea",
                      "summer", "martinique", "venison", "berries", "celeriac", "coating", "cone", "flank", "peel", "shortbread", "sampled",
                      "brine", "olive", "pot", "american", "bottom", "double", "pike", "popcorn", "rhubarb", "still",
                      "infusion", "swiss", "equal", "icing", "starch", "fries", "lightly", "soured", "special", "baking", "buckwheat", "celery", "energy", "garden", "junior",
                      "peeled", "single", "70", "bouillon", "burrito", "center", "commercially", "dill", "feed", "lingonberry", "omelette", "risotto",
                      "rump", "table", "dish", "kale", "leek", "liqueur", "mocha", "pretzels", "ravioli",
                      "sauerkraut", "14", "english", "hydrogenated", "parsley", "pepperoni", "vol", "25", "7", "base", "cocktail", "enfamil",
                      "fazer", "hindshank", "cheeseburger", "chicory", "cola", "grapefruit", "spelt", "turnip", "covered", "end", "flavors", "heavy", "horseradish", "mars", "melon",
                      "tart", "puffed", "rind", "us", "brussels", "graham", "less", "mexican", "plaice", "saarioinen", "vaasan", "cranberry",
                      "months", "puddings", "raisin", "baguette", "balls", "fennel", "lip", "topside", "bolognese",
                      "cafe", "dog", "palm", "sparkling", "spring", "swede", "artichoke", "probiotics", "snackfood", "9",
                      "king", "grated", "kohlrabi", "lidl", "nougat", "oscar", "types", "usda", "75", "mandarin", "mayer", "mead", "similac", "snack", "specialty", "sushi", "frying", "johnson", "lima",
                      "original", "ring", "shake", "simmered", "wafer", "elements", "formerly", "guava", "plums", "produced", "radish",
                      "values", "game", "long", "millet", "pirkka", "retail", "aubergine", "bitter", "chemical",
                      "commodity", "country", "marmalade", "meatballs", "mousse", "nutrition", "preparation", "stick", "sticks", "valio", "bake",
                      "brewed", "cherries", "condiments", "crepe", "new", "arm", "wok", "avocado",
                      "classic", "gratinated", "lasagna", "meatball", "meringue", "muffins", "ascorbic", "chanterelle", "chip",
                      "creme", "dha", "doughnut", "frosting", "fructose", "gingerbread", "gruel", "hash", "immature", "pastries", "brand", "caraway", "crunchy",
                      "rose", "dip", "grits", "microwaved", "n", "norwegian", "nutritional", "savoy", "v8", "ara", "bechamel", "courgette", "ginger", "japanese", "latte", "nestle", "shoots", "stage",
                      "strips", "be", "beet", "chowder", "clod", "farms", "fiber", "flounder", "pink", "siverside", "bulb", "cracker",
                      "silverside", "squares", "crunch", "de", "morningstar", "pop", "rtd", "strawberries",
                      "truffle", "basil", "blackberry", "blueberries", "couscous", "gooseberry", "date", "kebab", "lime", "pears",
                      "pies", "plate", "puffs", "roasts", "under", "au", "barbeque", "bell", "candied", "crispy", "croissant", "kissel", "off", "papaya", "parsnip",
                      "prune", "rusk", "curly", "spice", "artichokes", "bamboo", "barbecue", "crème", "lasagne",
                      "marzipan", "plus", "popped", "rum", "salsify", "skirt", "soda", "0.5", "bagel", "bars", "chard",
                      "citrus", "con", "juices", "lemonade", "pralines", "probiotic", "s", "school",
                      "zucchini", "abbott", "atria", "caffeine", "creams", "mini", "nuggets", "swedish", "toaster", "children", "crisps",
                      "cupcake", "hand", "hare", "karelian", "leeks", "m", "petite", "scrag", "spaetzle", "stalk",
                      "use", "vienna", "waffles", "wax", "apricots", "brawn", "cider", "german",
                      "good", "grapes", "minestrone", "outside", "peaches", "poached", "prunes", "snap", "spanish", 
                      "split", "start", "stuffing", "tapioca", "vit", "worthington", "yam", "applesauce", "boar", "bowls", "cube", "dumpling", "durum",
                      "fudge", "golden", "indian", "ketchup", "microwave", "punch", "sauces", "sautéed", "shortening",
                      "tap", "topped", "tub", "at", "averagely", "beverages", "bream", "commercial", "flatbread", "fleischkaese", "healthy",
                      "imitation", "lard", "lipil", "mock", "novelties", "parboiled", "pine", "pinto",
                      "post", "soufflé", "aspartame", "aspic", "bananas", "cottonseed", "gum", "ling", "mein",
                      "moist", "passion", "prime", "quince", "salsa", "strongly",
                      "taro", "whiskey", "x", "11", "17", "around", "asian", "bolete", "diabetics", "endive", "fricassee", "groats", "iceberg", "kiwi",
                      "milkshake", "nectarine", "old", "peppermint", "pita", "prego", "process", "reheated", "sapodilla", "spicy", "sport", "drinkable", "ultra",
                      "ball", "bits", "breadcrumbs", "cusk", "domestic", "fig", "giblets", "hk",
                      "lightened", "maple", "marshmallow", "pesto", "plantain", "pomegranate", "request", "roux", "rte",
                      "sapote", "size", "stroganoff", "tossed", "wrap", "blackcurrant", "brandy", "caesar", "caviar", "chayote",
                      "cob", "cracked", "entree", "fore", "gourd", "grill", "imported", "inside",
                      "k", "matjes", "ovenbaked", "pound", "quality", "raspberries", "russian", "spaghettios", "sprat",
                      "stews", "whiting", "bulgur", "clear", "collards", "cornflakes", "cress", "croquettes", "distilled",
                      "england", "enhanced", "fowl", "gefilus", "gin", "grams", "great", "greater", "mirabelle",
                      "navajo", "nettle", "pace", "18", "35", "big", "pickles", "pieces", "purple", "ranch",
                      "saccharin", "spritzer", "stir", "tangerine", "turnover", "varieties", "shaped", 
                      "vitasoy", "13", "bavarian", "birch", "boston", "cappuccino", "chinook", "chow", "coleslaw",
                      "crumbles", "eggplant", "fingers", "honeydew", "jars", "kraft", "lychee",
                      "paprika", "sand", "sauteed", "skewer", "smelt", "spiced", "strudel",
                      "sulfured", "sweets", "usa", "archway", "back", "beets", "breyers", "chives",
                      "consommé", "dandelion", "doughnuts", "flummery", "whipping", "milkfat", "greenland",
                      "hollandaise", "latino", "layer", "oululainen", "persimmon", "pumpernickel", "purchased", 
                      "radishes", "ripened", "saffron", "slim", "star", "sub", "supreme", "syrups", "t", "vodka", "2.5",
                      "85", "90", "argentine", "bittersweet", "breadfruit", "cheesecake", "chewy", "christmas",
                      "quail", "creamer", "currants", "dessert", "elderberry", "fatty", "g", "gherkins", "head", "hut",
                      "jack", "jellied", "jerusalem", "l", "liquorice", "lunch", "lungs", "main", "microwavable", "morel",
                      "pilchard", "plains", "prepackaged", "rock", "seasoning", "simple", "snellman", "spiny",
                      "splash", "spleen", "store", "treated", "tripe", "used", "acerola", "air", "bite", "blanched", "cape", "cheerios",
                      "component", "crumble", "deli", "elk", "gilde", "herbal", "links", "medlar", "microwaveable",
                      "moose", "nachos", "oxtail", "pretzel", "prickly", "purslane", "scalded", "scalloped", "stomach", "suey",
                      "swabian", "sweetbread", "tench", "tortellini", "tropical", "turnips", "28", "advance", "approx", "berlin",
                      "bifidus", "butternut", "carambola", "carbohydrate", "clementine", "club",
                      "cordial", "falafel", "flan", "fondant", "franks", "frosting", "garnish", "gerber",
                      "gnocchi", "greengage", "indians", "keiju", "linoleic", "little", "lower", "frostings",
                      "method", "mortadella", "nugget", "oriental", "polenta", "pops", "proof",
                      "prosobee", "rowanberry", "seasoned", "snickers", "sorbet", "sprout", "tree", "undiluted",
                      "very", "tri", "viennese", "wafers", "young", "16", "additives", "bites", "brioche",
                      "butt", "choux", "coarsely", "coriander", "etc", "gherkin", "halloumi", "hotdog", "krispies", 
                      "lake", "macaroon", "madiera", "mamey", "naranjilla", "praline", "remoulade", "roman", "savory", "sherbet",
                      "sherry", "shin", "softshell", "sorrel", "souffle", "soursoup", "spare", "sun", "watermelon", "à", "7.5",
                      "america's", "any", "picnic", "soursoup", "approximately", "arrowroot", "ayerst", "brook", "cherimoya", "chewing",
                      "cornbread", "couverture", "denver", "digestive", "durian", "elovena", "figs",
                      "fritter", "gold", "gram", "harvest", "hind", "hip", "hormel", "hyacinth", "jackfruit", "jujube",
                      "kitchen", "kokkikartano", "kumquat", "first", "loquat", "lardoons", "marble", "marrow", "moussaka", "nesquik", "pbm", "pheasant",
                      "porterhouse", "premium", "quesadilla", "refried", "relish", "removed", "rillettes", "rising", "rissoles",
                      "romaine", "rotisserie", "roulade", "safflower", "slicing", "smart", "south", "sports", "st", "sundae", "thyme", "toffee", "tonic", "trail",
                      "turkish", "watercress", "westphalian", "witch", "wyeth", "32", "98", "acidophilus", "alfalfa",
                      "bleached", "bowl", "boysenberry", "breadsticks", "brownie", "california", "caper",
                      "carbonara", "cardoon", "cordon", "crepes", "cubes", "cucumbers", "drinking", "dulce", "enchilada",
                      "fashioned", "foodstuffs", "freshly", "glazed", "go", "gumbo", "hearts", "lite", "loganberry",
                      "m's", "malabar", "melba", "mint", "multiple", "nacho", "natal", "nestlé", "nutrients", "oils",
                      "oranges", "ounce", "own", "pate", "pocket", "malted", "mammy", "mangosteen", "saddle", "salads",
                      "satsuma", "shad", "side", "sp", "surinam", "tagliatelle", "tallow", "tilsit", "tostada", "tvp", "unknown", "var", "winged",
                      "22", "24", "38", "6.25", "ab", "akee", "alfredo", "alpro", "arla", "assorted", "aubergines", "bagels", "becel",
                      "bolted", "bordelaise", "brittle", "bullock's", "cantaloup", "chain", "chanterelles", "chester", "chex", "coco",
                      "confectionery", "crescent", "crumb", "deepfried", "diary", "domino's", "drops", "e", "easy", "espresso",
                      "eyed", "farina", "flake", "flora", "froth", "globe", "glucose", "grey", "hominy", "hungarian",
                      "isomil", "jaboticaba", "label", "layered", "limburger", "mm", "moisture", "molasses", "mulberry", "multi",
                      "nasoya", "normally", "offal", "omega", "one", "packed", "pangasius", "passionfruit", "per", "perigord", "pointed",
                      "processing", "purée", "roots", "rosehip", "rosemary", "scale", "sockeye", "spirit", "spray", "square", "squeezed",
                      "stewing", "stinging", "tops", "thai", "tots", "truffles", "turnovers", "tzatziki", "valley", "vendance",
                      "warm", "wedges", "whoper", "zealand", "tail", "amarillo", "vendace", "whopper", "19", "23", "27", "allevo",
                      "allis", "basmati", "battered", "bearnaise", "benecol", "bilberry", "burgers", "burgundy", "butterkäse",
                      "cannelloni", "cantaloupe", "tamarillo", "chervil", "childrens", "crumbs", "diff", "falukorv", "farmer's", "filo", "fingre", "frankfurters",
                      "funnel", "hamburg", "household", "inconnu", "iodine", "is", "jagwurst", "leavening", "linda", "loma", "lotus",
                      "manioc", "marshmallows", "medley", "minute", "jagwurst", "multivitamin", "nature", "o's", "panini",
                      "picked", "pitted", "polar", "polish", "portion", "price", "propionate", "purpose",
                      "quiche", "ralston", "rings", "royal", "schupfnudeln", "self", "semper", "silken", "slippery",
                      "stevia", "swirl", "tamale", "thousand", "tra", "traditional", "wendy's", "whitener", "wieners", "witloof", "0.1",
                      "55", "63", "73", "alpine", "anise", "b12", "baby's", "bakes", "basis", "bergkäse", "blackberries", "bloomy", "borage", "brussels's",
                      "buns", "buttered", "caramels", "champagne", "char", "chilli", "chutney", "compressed", "convenience", "digiorno",
                      "dogs", "finnish", "gourmet", "guacamole", "hearty", "jasmine", "joy", "kits", "koch", "lauantai", "leipäaitta",
                      "limas", "loops", "lye", "lyoner", "mac", "macaroons", "macchiato", "manhattan", "mountain", "muenster", "nabisco",
                      "naturdiet", "navy", "nutramigen", "nutri", "nutrilett", "oatly", "oivariini",
                      "oumph", "ox", "pak", "parfait", "parma", "petit", "pickle", "pomelo", "port", "potassium", "powan",
                      "pressed", "quenelle", "rocket", "rosé", "sage", "scotch", "sliceable", "slow", "sourdough", "spam", "string",
                      "strong", "sturgeon", "submarine", "succotash", "sulfate", "super", "superior", "supper", "surrogate", "terrine", "thuringian",
                      "toppings", "toro", "total", "triple", "venus", "vermicelli", "vinaigrette", "weed", "wonton", 
                      "0.9", "34", "65", "82", "acorn", "allerlei", "bee", "berliner", "braided", "canadian", "cap'n", "catering", "certified",
                      "chimichanga", "chitterling", "choi", "chou", "cobbler", "coffeecake", "cognac", "consomme", "cook", "cos",
                      "crookneck", "croquette", "cup", "cutlet", "dab", "degermed", "delight", "drippings", "eastern", "eclair", "eggo",
                      "empanada", "escarole", "fallow", "feet", "felix", "fillings", "findus", "fondue", "fontina", "forequarter", "forest",
                      "four", "fritters", "fully", "galantine", "gatorade", "glaze", "gooseberries", "gras", "griddle",
                      "grilling", "hashed", "higher", "härkis", "i", "klondike", "leipziger", "link", "lion", "lump", "marathon",
                      "marie", "marjoram", "masa", "masala", "matzo", "mcdonalds", "meatfat", "merguez",
                      "mg", "müllerin", "next", "novelle", "offals", "orache", "oregano", "paella", "pakari", "pale", "par", "pikes",
                      "pillsbury", "precooked", "prior", "profeel", "quarter", "radicchio", "ratatouille", "reese's", "rennin", "romadur",
                      "romanesco", "rutabaga", "saint", "sandwiches", "saveloy", "sensitive", "shallots", "southern", "spirits", "sting",
                      "straightneck", "suisse", "tamarind", "tarragon", "tenders", "three", "tikka", "tlc", "vacuum", "vita", "way",
                      "wedding", "weetabix", "wiener", "woven", "37", "5.5", "58", "650", "95", "ale", "always", "anglaise", "antell",
                      "appenzeller", "aroma", "arroz", "assortment", "autumn", "balsam", "bay", "bearded", "bed", "beginnings", "bengal",
                      "biola", "bircher", "bisquit", "blintzes", "bouillabaisse", "breads", "brownies", "burbot", "vermouth", "yardlong", "agar", "bright", "butterscotch", "caesars",
                      "caffe", "cambridge", "cappucino", "caramelised", "carb", "chik'n", "choco", "chokeberry", "cholesterol", "chrysanthemum", "chum", "cocoavia", "coho",
                      "colada", "colby", "cranberries", "croutons", "decorticated", "dietetic", "diplom", "eldorado", "essentials", "fajita", "family", "feijoa", "fitness",
                      "flavours", "florida", "foil", "friday's", "cones", "confection", "confectioner's", "containing", "coop", "fruity", "gazpacho", "gentle", "gentlease", "gravad", 
                      "gutted", "hennig", "hershey's", "hickory", "hopi", "human", "hälsans", "include", "intended", "italien", "its", "jalapeno", "juniper", "jute", "kabob", "kaiserschmarrn",
                      "kartanon", "katri", "krakauer", "kök", "lager", "lait", "lo", "local", "louis", "lounto", "major", "margherita", "mass", "menu", "minerals", "mold",
                      "monster", "norway", "og", "oleic", "olsen", "oogruk", "oreo", "pancreas", "particularly", "partly", "pastille", "pastrami", "paté", "perheleipurit",
                      "piano", "pilaf", "pirogue", "pockets", "principal", "pro", "pupusas", "pågen", "podded", "rhenish", "salisbury", "saltine", "schär", "smooth", "snow",
                      "spotted", "steller", "step", "stollen", "striped", "subcutaneous", "subway", "tablets", "talkkuna", "time", "tine", "tips", "tortillas", "truffled", "uk",
                      "uses", "velvety", "0,5", "0.2", "1,2", "1000", "1700", "1800", "2.7", "2.9", "4.4", "4.7", "72", "96", "agave", "ajvar", "alimentum", "aloe", "applebee's",
                      "arugula", "b2", "balance", "balm", "barrel", "basque", "batata", "bierwurst", "bisque", "blanc", "bok", "borek", "bottle", "box", "brussel", "bunches", "burdock",
                      "blau", "bush", "butterbur", "caffeinated", "calabash", "calzone", "campari", "cane", "cayenne", "centre", "cervelat", "channel", "chipotle", "collar", "coral",
                      "covering", "crowder", "chews", "crunch's", "cuban", "cubed", "cyclamate", "daiquiri", "dampfnudeln", "dates", "december", "denny's", "dove", "down", "elbow",
                      "essence", "femoris", "flageolet", "focaccia", "foo", "franco", "freshwater", "frödinge", "gaisburger", "garland", "gelbwurst", "giant", "glutinous", 
                      "gordita", "gravity", "grillers", "hipp", "golean", "homestyle", "hubbard", "incomplete", "ingmariini", "iodised", "irish", "jacky", "jansson's", "jar",
                      "john's", "jyväshyvä", "kassler", "knackebrot", "knacker", "kung", "königsberger", "leberkäse", "lolly", "looseleaf", "lu", "lung", "magnesium", "maria", "maroilles",
                      "marsch", "mekukatti", "meieriene", "mimolette", "monterey", "mori", "mulled", "müsli", "naturell", "neapolitan", "nonalcoholic", "mehukatti", "norvegia", "nu", "pad",
                      "palatinate", "panna", "pao", "paris", "parsnips", "pichelsteiner", "pina", "point", "popsicle", "portabella", "pounder", "power", "powerade", "q", "ramen",
                      "rendered", "ribbon", "rinsed", "ritz", "rosti", "rough", "ruffled", "runner", "rypsi", "réunion", "sago", "saltines", "santa", "sauerbraten", "scones", "seasonings", "sheet",
                      "shepherd's", "shortribs", "shot", "sloe", "slush", "snapper", "sorbitol", "spit", "spoon", "stabburet", "stalks", "stem", "sterols", "strip",
                      "sugared", "swanson", "t.g.i", "tabletop", "tamarinds", "tequila", "tiramisu", "tortes", "turmeric", "twix", "ullan", "unbaked", "uncle", "v", "vanillin", "various",
                      "vent", "walrus", "wasabi", "xylitol", "yosa", "yung", "0.3", "0.8", "1,0", "21", "26", "3.25", "39", "4,5", "4.5", "5.70", "500", "59", "abalone",
                      "acetic", "alc", "amp", "apache", "ar", "aromatic", "b", "baden", "bbq", "buddig", "bundt", "burnet", "cabanossi", "cafeteria", "café", "canderel",
                      "caramelized", "cardamom", "caribbean", "carl", "child", "chine", "chitterlings", "chive", "biryani", "blin", "bog", "brassica",
                      "braunschewiger", "bregott", "bud", "chik", "chocolat", "choy", "cloudberries", "cloudberry", "clusters", "complete",
                      "congee", "cornish", "cortado", "crisphead", "cumin", "curried", "danbo", "dexal", "dock", "drop", "eila", "el", "ensure",
                      "essences", "exotic", "export", "express", "fats", "february", "fed", "fjordland", "flavourings", "florentine", "flower", "flowers", "fluoride",
                      "frik", "fudgesicle", "fusion", "glandless", "glass", "glazing", "gnld", "grahams", "granny", "groat", "hawaii", "hawaiian", "helene", "item", "jams",
                      "january", "jicama", "jowl", "jr", "june", "kalops", "keebler", "kid's", "kidius", "kippered", "klopse", "kuri", "lahmacun", "lambsquarters", "leather",
                      "lecithin", "life", "lindström", "lingonberries", "linkosuo", "loaded", "lobscouse", "log", "lollipop", "lucerne", "lätta", "manicotti", "maracuja",
                      "martha", "max", "mechanically", "melange", "middle", "milanese", "miscellaneous", "mix'n", "mocca", "more", "mould", "mr", "mush", "nalle", "naturli",
                      "nem", "newman's", "nicoise", "nordfjord", "north", "oh", "origins", "osso", "over", "packaged", "paneer", "papa", "paso", "phoenix", "phyllo", "pierogi",
                      "pitta", "poke", "popsickle", "poulard", "pregestimil", "primal", "prob", "plantains", "plantego", "platter", "pod", "promise", "provencal", "provençal", "pupusa",
                      "pâtés", "queen", "rambutan", "range", "rate", "ray", "redcurrant", "reilu", "reissumies", "risi", "risifrutti", "rockstar", "rosso", "ruispalat", "rumpsteak", "rusks",
                      "sabayon", "sacher", "salut", "sambusa", "sauté", "scarlett", "schinkenwurst", "scooped", "serbian", "sesbania", "shashlik", "shoot", "shortcake", "six", "skinless",
                      "skittles", "slider", "smith", "smokies", "snøfrisk", "solid", "sopa", "southwest", "spiral", "starburst", "starchy", "steinbuscher", "streaky", "styles",
                      "sucker", "sucralose", "sugars", "supplement", "swamp", "swirls", "tabbouleh", "tangerines", "taquito", "tartlet", "tasty", "thuringer", "thymus", "toasting", "tomme",
                      "trotter", "tusk", "tutti", "twists", "tyrolean", "ultimate", "unleavened", "vault", "verde", "voi", "waldorf", "walleye", "washed", "whelk", "waxgourd", "weighted", "zero", 
                      "zest", "0.4", "1.4", "1.7", "11.5", "15.5", "2.3", "3,5", "3.6", "33", "43", "44", "52", "54", "84", "accompaniments", "actimel", "active", "activia", "adobo", "advantage", "age",
                     "agent", "agutuk", "aioli", "al", "alaskan", "almondy", "ambrosia", "an", "analyzed", "angelfood", "aperitif", "aquavit", "arctic", "areas", "arrowhead", "aspartam",
                     "august", "avocados", "azumaya", "avocados", "baba", "bakeries", "bakers", "baklava", "balkan", "balsamic", "bayonne", "beach", "been", "beerwurst", "beestings", "ben",
                     "ben's", "bicarbonate", "birth", "blackcurrants", "blanket", "blossom", "blå", "bock", "bohemian", "bolar", "bonjour", "bottoms", "bowhead", "breadnut", "brewer's", "brick",
                     "béarnaise", "béchamel", "cactus", "calvados", "can", "carcass", "caribou", "carlshamn", "carnation", "carton", "casei", "catalina", "catjang", "ceviche", "chamomile",
                     "chantarelle", "chapati", "charlotte", "chasseur", "cheesy", "cheez", "cheez", "chevre", "chipped", "chèvre", "ciabatta", "cilantro", "clif", "cloves", "coarsly", "cobs",
                     "colossal", "condiment", "consistency", "cornet", "cornpops", "cotta", "cotton", "coulis", "cowberries", "cowberry", "creamsicle", "crinkle", "crispies", "croaker", "croissan'wich", "croissants",
                     "crottin", "crêpes", "cumberland", "curacao", "curing", "custards", "cythère", "d'or","daikon", "day", "debrecziner", "devil's", "different", "dipmix", "dishcloth", "dolma", "cotto", "doritos",
                     "dream", "dressed", "duchesse", "duty", "earth", "effect", "enfagrow", "entrecote", "entrees", "esrom", "except", "exposed", "extracts", "false", "fear", "fenugreek", "filberts",
                     "filmjölk", "finax", "finely", "fireweed", "fiskgrateng", "florence", "flowered", "flädle", "foot", "fordhook", "forelle", "fresco", "fricandeau", "fritolay", "fritos", "froot",
                     "frothed", "fruitcake", "fruiting", "frukostkorv", "fuit", "fun", "ghee", "gilthead", "grouper", "health", "hens", "herbalife", "hessian", "himmelreich",
                     "hjertego", "hocks", "hoff", "hoisin", "horeca", "hotcakes", "house", "hull", "hush", "husked", "husman", "hyvää", "ica", "igneous", "incl", "ingman", "international", "isoäidin", "isrish",
                     "jaffa", "jarlsberg", "jellies", "joe", "jus", "fiskegrateng", "gingersnaps", "goa", "gogreen", "goreng", "grade", "grenadier", "grießnockerln", "grilstad", "kariniemi", "kasseler",
                     "kat", "kaura", "kentucky", "kevyt", "kir", "korean", "kombu", "kretschmer", "kudos", "landjäger", "lapin", "lauric", "leader", "lefse", "licorice", "lily", "liqourice", "lounassämpylä", "lumpsucker",
                     "luxury", "maarud", "mace", "madeleine", "malakoff", "maltex", "mammee", "maraschino", "marinara", "martini", "matured", "may", "maypo", "mcgriddles", "mcmuffin", "melons", "menthe",
                     "middagskorv", "milda", "miniature", "minihiilari", "moilas", "mole", "molokhia", "mont", "mosaic", "mostly", "mud", "muskmelon", "musli", "margarita", "marsala", "muzzle", "nance",
                     "napoleon", "nectaire", "nestea", "nettles", "nordic", "nutella", "nycoplus", "o'brien", "ogeu", "olestra", "pakarin", "parisian", "patterned", "paupiette", "pe", "pectin", "pediasure",
                     "pepperpot", "persimmons", "pfefferpotthast", "pimento", "pimiento", "pinot", "pokeberry", "polished", "pond", "pop'ables", "popeyes", "potherb", "pout", "premature", "preserves",
                     "preserving", "pressure", "pressurized", "presweetened", "prince", "printen", "proviva", "ptarmigan", "päivää", "quarg", "quarters", "pips", "quinine", "recovery", "risalamande",
                     "rohrnudeln", "rounds", "royale", "rukiinen", "rutabagas", "rösti", "sallad", "sangria", "schlesisches", "sections", "semisweet", "served", "shoyu", "similar", "sin",
                     "skipjack", "sloppy", "smoke", "smoothies", "spritz", "squab", "stars", "sticker", "stilton", "stockpot", "storage", "stove", "spears", "sprinkles", "sunchips", "sunnuntai", "sunny",
                     "sunrise", "tahitian", "taikaruis", "temptation", "tempura", "tendergreen", "thompson", "tiger", "tarhonya", "toffees", "touch", "towelgourd", "treats", "triangle", "trotters", "tsai",
                     "tumma", "twizzlers", "täyshyvät", "töttchen", "up", "upside", "unbleached", "valencia", "varmkorv", "vegme", "virginia", "weisslacker", "whisky", "welsh", "wheatena",
                     "willow", "wilstermarsch", "velvet", "woks", "worcestershire", "0.75", "1.2", "110", "14.5", "150", "1ug", "2,1", "2.2", "2.6", "2.8", "2,5", "2007", "3.3", "3.7",
                     "31", "36", "4,6", "4,7", "4.2", "48", "51", "53", "57", "61", "62", "630", "69", "8.5", "86", "94", "99", "aamiaisleipä", "ace", "acesulfame", "acids", "acorns", "acting",
                     "additional", "ahlgrens", "aktiivi", "alkali", "alkaline", "alku", "allgäu", "allspice", "alpha", "alrpo", "alsatian", "amerikan", "ananas", "anejo","angler", "antioxidants",
                     "apetit", "arabic", "arizona", "arkipaahto", "armenian", "arrack", "asadero", "asiago", "asterix", "aura", "automn", "ayran", "b6", "backfat", "bagged", "baconburger", "bains", "ballerina",
                     "bannock", "bao", "beat", "beefburger", "bel", "belle", "benner", "bernaise", "betty", "bianca", "biff", "bilar", "bird", "biscotti", "beefalo", "biscuit", "bisquits", "blindhuhn",
                     "block", "blodbröd", "blond", "bloody", "blt", "bolied", "bonaqua", "boost", "borsch", "borscht", "borschtsch", "bottles", "boxed", "boysenberries", "breading", "break", "breakstone's",
                     "bremen", "bremykt", "bresse", "breton", "brisoletten", "broccoflower", "brungräddat", "bruschetta", "brûlée", "bucco", "buche", "buco", "budweiser", "bulgarian", "bumpers",
                     "burst", "but", "buttercream", "butterkeks", "buttery", "bäckerinkartoffeln", "cabernet", "cabinet", "caen", "caesar's", "calamari", "canneloni", "cantal", "capelin",
                     "buds", "capon", "caprese", "capricciosa", "care", "caressed", "carneval", "carte","casing", "cast", "catago", "catalan", "catsup", "cellophane", "challah", 
                     "character", "charms", "charr", "chemicals", "chequerboard", "cheshire", "chiles", "chilies", "chilisauce", "china", "chipolata", "chloride", "choskecherries",
                     "christophine", "cisco", "claws", "coatings", "cobb", "cocktails", "collected", "combos", "conger", "connective", "contents", "control", "cool", "cornbased", "cornichons"])

    # Alternative or Traditional
   df_source_type = pd.DataFrame(data={'protein_source':['Chicken', 'Egg', 'Pork', 'Milk', 'Oat', 'Peas', 'Wheat', 'Soy','Beef', 'Potato', 'Faba bean', 'Chickpea', 'Dairies', 'Rapeseed','Quinoa', 'Lentil', 'Microalgae', 'Single cell bacteria', 'Cricket','Cultured beef', 'Hemp', 'Leaf protein', 'Algal fraction', 'Brewer´s spent grain', 'Spirulina', 'Fish side stream', 'Krill'], 
       'source_type':['Traditional', 'Traditional', 'Traditional', 'Traditional', 'Plant', 'Plant', 'Plant', 'Plant', 'Traditional', 'Plant', 'Plant', 'Plant', 'Traditional', 'Plant', 'Plant', 'Plant', 'Ocean-based', 'Microbe & fungal', 'Insect', 'Cultured meat', 'Plant', 'Plant', 'Ocean-based', 'Plant', 'Ocean-based', 'Ocean-based', 'Ocean-based']})

   df_essentiality = pd.DataFrame({'amino_acid_name':['Tryptophan (Trp/W)','Valine (Val/V)', 'Alanine (Ala/A)','Tyrosine (Tyr/Y)', 'Isoleucine (Ile/I)', 'Threonine (Thr/T)','Serine (Ser/S)', 'Leucine (Leu/L)', 'Glutamic acid (Glu/E)',
                'Arginine  (Arg/R)', 'Glycine (Gly/G)', 'Methionine (Met/M)','Lysine (Lys/K)', 'Aspartic Acid (Asp/D)', 'Histidine  (His/H)','Phenylalanine (Phe/F)', 'Proline (Pro/P)', 'Cysteine (Cys/C)','Taurine'],
             'essentiality':['Essential', 'Essential', 'Non-Essential', 'Non-Essential', 'Essential', 'Essential', 'Non-Essential', 'Essential', 'Non-Essential', 'Non-Essential', 'Non-Essential', 'Essential',
                             'Essential', 'Non-Essential', 'Essential', 'Essential', 'Non-Essential', 'Non-Essential', 'Non-Essential']})

   df_protein_sources = pd.DataFrame(data={'protein_source':['Faba bean', 'Lentil', 'Oat', 'Quinoa', 'Rapeseed', 'Microalgae', 'Single cell bacteria', 'Cricket', 'Cultured beef', 'Hemp', 'Leaf protein', 'Algal fraction',
                                     'Soy', 'Wheat', 'Peas', 'Chickpea', 'Potato', 'Brewer´s spent grain', 'Spirulina', 'Fish side stream', 'Krill', 'Beef', 'Pork', 'Chicken', 'Egg', 'Milk', 'Dairies']})

   parameters = locals().copy()
   return parameters